### PR TITLE
PUI-4428: Add Support for Soft Commits

### PR DESCRIPTION
**Pull request by amcaplan**
This already exists in upstream Sunspot, just applying the patch here as well.

### CODE REVIEW

**Comment by robincurry** [comment]
Woot!

**Comment by nwp** [comment]
Any potential of getting this into the official Sunspot project?

**Comment by robincurry** [comment]
@nwp that's where it came from. we are just applying to our fork here.

**Comment by robincurry** [comment]
also, sad face that we are maintaining a fork. :(

**Comment by amcaplan** [comment]
Yeah, is there a way to just get all the upstream stuff?

**Pull request merged**
