### PR TITLE
Updates for Rails 5

### PR DESCRIPTION
**Pull request by mrchucho**
* after_action replaces after_filter
* Rails 2's prepend method replaces alias_method_chain

I _think_ reasoned the use of prepend properly?? Hoping a spec will let me know for sure.

### CODE REVIEW

**Comment by mrchucho** [comment]
Oh yeah, now I remember travis doesn't really work for this gem. Blargh.

I'm using this branch locally in etl and its specs are passing. So, that's encouraging.

**Comment by mrchucho** [comment]
Ah, thanks @wbajzek. Should I just copy those upstream changes or is there a good way to merge/update from upstream?

**Comment by wbajzek** [comment]
Hmm... could you try cherry-picking this commit? https://github.com/sunspot/sunspot/commit/fac47da6e4ffbb4262b987be1d04ff2f2d49ac99#diff-0bcbc85bfe3f45a33fb8cd7d62c0146b

**Comment by mrchucho** [comment]
OK, I reverted my commits and cherry-picked that upstream PR's commit.

**Comment by mrchucho** [comment]
Thanks!

**Pull request merged**
