### PR TITLE
Upgrades to solr 4.10.4

### PR DESCRIPTION
**Pull request by thegene**
This might be the shortest lift to accommodate @amcaplan 's need for a more up-to-date solr. I could also be doing this way wrong. @mrchucho @robincurry  ?

### CODE REVIEW

**Comment by amcaplan** [comment]
Much of this isn't necessary, though it doesn't really hurt because solr here is a mess to start with, so whatever.  I managed a minimal setup at https://github.com/mdx-dev/platform-search/pull/228 with 25 files, rather than 644.  All you need is the Solr war file, jetty & configs.  The rest is an example solr home which we don't need in our case.  Doesn't hurt to update, but this is a lot of files.

**Comment by amcaplan** [comment]
This was the commit that includes the necessary 25 files.  (Technically README wasn't a necessary file, but you get the idea.)

**Comment by amcaplan** [comment]
etc & lib directories, start.jar and solr.war

That said, I can't be sure, because I don't know how SunspotTest works exactly, so may require a bunch of other junk.

**Comment by robincurry** [comment]
Yeah, looking at previous solr upgrade commits in the project (i.e. https://github.com/mdx-dev/sunspot/commit/f402124bc9bbebfbb389021bbda4ac08a4ab021e), for minor version updates it was just jars and wars mostly.

**Comment by amcaplan** [comment]
Looking at that commit, seems like lib, start.jar, webapps/solr.war - and etc isn't even necessary!

**Comment by amcaplan** [comment]
Also, if you want to see the whole diff: https://patch-diff.githubusercontent.com/raw/mdx-dev/sunspot/pull/21.diff

Don't let it crash your browser!

Just thought that was pretty cool.  GitHub magic!

**Comment by amcaplan** [comment]
Accessible at https://github.com/mdx-dev/sunspot/pull/21.diff

**Comment by thegene** [comment]
rtftpupvhikjk

JAR WARS!

**Comment by robincurry** [comment]
Haha.

**Comment by amcaplan** [comment]
I think you mean... har har.

**Comment by robincurry** [comment]
actually @amcaplan, I think I was just thinking about this PR.... which never got merged. Anyone know where this stands?

**Comment by amcaplan** [comment]
If it passes, no reason not to merge it, right?

**Comment by amcaplan** [comment]
Oh wait, no CI here, oops.  Maybe we can suffice with a local test, or push up an ETL branch for CI that depends on this?

**Pull request closed without merging**
